### ISSUE TITLE
[Bug] # is not support in Template

### ISSUE THREAD

**Issue by liuh886** [niondevi/clipsidian#3]
Great design! 

The test case fails to send any text containing character  # in Template.

**Comment by xEdelweiss** [comment]
It is not encoded but works if you write `%23` instead of `#` in a template.

**Comment by ksdavidc** [comment]
I think you should include this in the instructions.

**Comment by ksdavidc** [comment]
are there any other forbidden characters that must be encoded?

**Comment by xEdelweiss** [comment]
@ksdavidc, I am not a developer of the clipsidian, just had the same issue
